In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

C:\Users\Admin\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [5]:
from sklearn.model_selection import GridSearchCV

In [6]:
from sklearn import svm

In [10]:
data=pd.read_csv("spam.csv")
data

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB

In [19]:
X=data["Email No."].values

In [20]:
Y=data["a"].values

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [25]:
cv=CountVectorizer()

In [26]:
X_train=cv.fit_transform(X_train)

In [27]:
X_test=cv.transform(X_test)

In [28]:
print(X_train)

  (0, 4129)	1
  (0, 2066)	1
  (1, 4129)	1
  (1, 3030)	1
  (2, 4129)	1
  (2, 2702)	1
  (3, 4129)	1
  (3, 2227)	1
  (4, 4129)	1
  (4, 2834)	1
  (5, 4129)	1
  (5, 500)	1
  (6, 4129)	1
  (6, 3700)	1
  (7, 4129)	1
  (7, 3552)	1
  (8, 4129)	1
  (8, 799)	1
  (9, 4129)	1
  (9, 2843)	1
  (10, 4129)	1
  (10, 3385)	1
  (11, 4129)	1
  (11, 665)	1
  (12, 4129)	1
  :	:
  (4124, 1090)	1
  (4125, 4129)	1
  (4125, 1012)	1
  (4126, 4129)	1
  (4126, 1441)	1
  (4127, 4129)	1
  (4127, 3865)	1
  (4128, 4129)	1
  (4128, 2208)	1
  (4129, 4129)	1
  (4129, 3014)	1
  (4130, 4129)	1
  (4130, 30)	1
  (4131, 4129)	1
  (4131, 3426)	1
  (4132, 4129)	1
  (4132, 3489)	1
  (4133, 4129)	1
  (4133, 2015)	1
  (4134, 4129)	1
  (4134, 580)	1
  (4135, 4129)	1
  (4135, 1447)	1
  (4136, 4129)	1
  (4136, 1555)	1

In [29]:
print(X_test)

  (0, 4129)	1
  (1, 4129)	1
  (2, 4129)	1
  (3, 4129)	1
  (4, 4129)	1
  (5, 4129)	1
  (6, 4129)	1
  (7, 4129)	1
  (8, 4129)	1
  (9, 4129)	1
  (10, 4129)	1
  (11, 4129)	1
  (12, 4129)	1
  (13, 4129)	1
  (14, 4129)	1
  (15, 4129)	1
  (16, 4129)	1
  (17, 4129)	1
  (18, 4129)	1
  (19, 4129)	1
  (20, 4129)	1
  (21, 4129)	1
  (22, 4129)	1
  (23, 4129)	1
  (24, 4129)	1
  :	:
  (1010, 4129)	1
  (1011, 4129)	1
  (1012, 4129)	1
  (1013, 4129)	1
  (1014, 4129)	1
  (1015, 4129)	1
  (1016, 4129)	1
  (1017, 4129)	1
  (1018, 4129)	1
  (1019, 4129)	1
  (1020, 4129)	1
  (1021, 4129)	1
  (1022, 4129)	1
  (1023, 4129)	1
  (1024, 4129)	1
  (1025, 4129)	1
  (1026, 4129)	1
  (1027, 4129)	1
  (1028, 4129)	1
  (1029, 4129)	1
  (1030, 4129)	1
  (1031, 4129)	1
  (1032, 4129)	1
  (1033, 4129)	1
  (1034, 4129)	1

In [30]:
from sklearn.svm import SVC

In [33]:
classifier=SVC(kernel='rbf',random_state=0)

In [34]:
classifier.fit(X_train,Y_train)

SVC(random_state=0)

In [35]:
print(classifier.score(X_test,Y_test))

0.04830917874396135